# Generated by Django 4.2.15 on 2024-09-03 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_community",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="JoinCommunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join", models.BooleanField()),
                ("join_community", models.ManyToManyField(to="blog.community")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joining_community",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
