# Generated by Django 4.2.15 on 2024-09-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_community_user_joincommunity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="url",
        ),
        migrations.AddField(
            model_name="post",
            name="community",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community",
                to="blog.community",
            ),
        ),
    ]
