# Generated by Django 4.2.15 on 2024-09-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_title_community_community_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="community",
            old_name="community_name",
            new_name="name",
        ),
    ]
