# Generated by Django 4.2.15 on 2024-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_rename_community_name_community_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="slug",
            field=models.SlugField(
                default=None, max_length=500, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
