# Generated by Django 4.2.15 on 2024-09-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_community_slug_alter_community_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="slug",
        ),
    ]
