# Generated by Django 4.2.15 on 2024-09-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_community_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="community",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="community",
            name="user",
        ),
    ]
